

3rd party contributions:
    - '(3rd party contributions)'

5 minute fix:
    - '(5 minute fix)'

accessibility ♿:
    - '(accessibility ♿)'

additives:
    - '(additives)'

admin tools:
    - '(admin tools)'

advanced search:
    - '(advanced search)'

agribalyse:
    - '(agribalyse)'

alcohol:
    - '(alcohol)'

allergens:
    - '(allergens)'

animal welfare:
    - '(animal welfare)'

anonymous-edits:
    - '(anonymous-edits)'

apache:
    - '(apache)'

api auth:
    - '(api auth)'

api quality:
    - '(api quality)'

API read:
    - '(API read)'

API write:
    - '(API write)'

API:
    - '(API)'

argentina:
    - '(argentina)'

Attributes:
    - '(Attributes)'

automatic-data-augmentation:
    - '(automatic-data-augmentation)'

automation:
    - '(automation)'

autorelease: pending:
    - '(autorelease: pending)'

autorelease: tagged:
    - '(autorelease: tagged)'

autosuggest:
    - '(autosuggest)'

averages by categories:
    - '(averages by categories)'

barcodes:
    - '(barcodes)'

best-before-dates:
    - '(best-before-dates)'

Big Bang for Your Time:
    - '(Big Bang for Your Time)'

Blocking Hunger Games:
    - '(Blocking Hunger Games)'

blocking mobile apps:
    - '(blocking mobile apps)'

blocking-smoothie:
    - '(blocking-smoothie)'

brands:
    - '(brands)'

brokenlinks:
    - '(brokenlinks)'

bug:
    - '(bug)'

Buggy products:
    - '(Buggy products)'

caching:
    - '(caching)'

can't reproduce:
    - '(can't reproduce)'

can-be-done-by-robotoff:
    - '(can-be-done-by-robotoff)'

carbon footprint:
    - '(carbon footprint)'

categories:
    - '(categories)'

category-specific support:
    - '(category-specific support)'

changelog:
    - '(changelog)'

charts:
    - '(charts)'

checkbot:
    - '(checkbot)'

Checked products:
    - '(Checked products)'

China:
    - '(China)'

ci
Continuous integration:
    - '(Continuous integration)'

ciqual:
    - '(ciqual)'

comments:
    - '(comments)'

compare:
    - '(compare)'

contribution journey:
    - '(contribution journey)'

CORS:
    - '(CORS)'

CRON
cropping:
    - '(cropping)'

css:
    - '(css)'

csv exports:
    - '(csv exports)'

darkmode:
    - '(darkmode)'

data destroying issue:
    - '(data destroying issue)'

data donations:
    - '(data donations)'

data export:
    - '(data export)'

data extraction:
    - '(data extraction)'

data import:
    - '(data import)'

data quality:
    - '(data quality)'

data4good-environment:
    - '(data4good-environment)'

data-freshness:
    - '(data-freshness)'

data-quality-nutrition:
    - '(data-quality-nutrition)'

debug:
    - '(debug)'

delta exports:
    - '(delta exports)'

dependancies:
    - '(dependancies)'

dependencies:
    - '(dependencies)'

deploy-dev:
    - '(deploy-dev)'

deployed-on-dev-server:
    - '(deployed-on-dev-server)'

design:
    - '(design)'

dev:
    - '(dev)'

devops:
    - '(devops)'

diluted products:
    - '(diluted products)'

disk space:
    - '(disk space)'

Display:
    - '(Display)'

docker:
    - '(docker)'

documentation:
    - '(documentation)'

documentation-update-required:
    - '(documentation-update-required)'

documented:
    - '(documented)'

donations:
    - '(donations)'

drip editing:
    - '(drip editing)'

driveoff:
    - '(driveoff)'

duplicate:
    - '(duplicate)'

ecoscore:
    - '(ecoscore)'

edit rules:
    - '(edit rules)'

editing:
    - '(editing)'

editing-images:
    - '(editing-images)'

education:
    - '(education)'

eggs:
    - '(eggs)'

elastic:
    - '(elastic)'

elk:
    - '(elk)'

Emails:
    - '(Emails)'

encoding:
    - '(encoding)'

environment:
    - '(environment)'

Epic:
    - '(Epic)'

♞ epic:
    - '(♞ epic)'

equivalents:
    - '(equivalents)'

export:
    - '(export)'

facets:
    - '(facets)'

favicons:
    - '(favicons)'

feature:
    - '(feature)'

fishing:
    - '(fishing)'

fixable-in-crowdin:
    - '(fixable-in-crowdin)'

fixable-via-userscript:
    - '(fixable-via-userscript)'

fixed?:
    - '(fixed?)'

fixed-via-userscript:
    - '(fixed-via-userscript)'

folksonomy project:
    - '(folksonomy project)'

food archeology:
    - '(food archeology)'

Food groups:
    - '(Food groups)'

Food.pm:
    - '(Food.pm)'

footer:
    - '(footer)'

foreign-products-stored-in-french:
    - '(foreign-products-stored-in-french)'

forest footprint:
    - '(forest footprint)'

foundation:
    - '(foundation)'

france:
    - '(france)'

frontend:
    - '(frontend)'

gamification:
    - '(gamification)'

geolite:
    - '(geolite)'

German:
    - '(German)'

github_actions:
    - '(github_actions)'

gluten:
    - '(gluten)'

good first issue:
    - '(good first issue)'

graphs:
    - '(graphs)'

GS1:
    - '(GS1)'

Hacktoberfest:
    - '(Hacktoberfest)'

halal:
    - '(halal)'

health card:
    - '(health card)'

help wanted:
    - '(help wanted)'

homepage:
    - '(homepage)'

How much sugar:
    - '(How much sugar)'

html:
    - '(html)'

HTTPS:
    - '(HTTPS)'

hunger games:
    - '(hunger games)'

i18n:
    - '(i18n)'

icons:
    - '(icons)'

ideas:
    - '(ideas)'

image recognition:
    - '(image recognition)'

image upload:
    - '(image upload)'

ImageMagick:
    - '(ImageMagick)'

images:
    - '(images)'

impact:
    - '(impact)'

india:
    - '(india)'

infoboxes:
    - '(infoboxes)'

infrastructure:
    - '(infrastructure)'

ingredient-list-cutting:
    - '(ingredient-list-cutting)'

ingredients analysis:
    - '(ingredients analysis)'

ingredients:
    - '(ingredients)'

installation:
    - '(installation)'

invalid:
    - '(invalid)'

javascript:
    - '(javascript)'

keyboard shortcuts:
    - '(keyboard shortcuts)'

Knowledge panels:
    - '(Knowledge panels)'

knowledge-panels:
    - '(knowledge-panels)'

labels:
    - '(labels)'

lactose:
    - '(lactose)'

lazy-loading:
    - '(lazy-loading)'

legacy:
    - '(legacy)'

linked data:
    - '(linked data)'

List pages:
    - '(List pages)'

location:
    - '(location)'

logos:
    - '(logos)'

Made Near Me:
    - '(Made Near Me)'

maintenance:
    - '(maintenance)'

Makefile:
    - '(Makefile)'

manifest:
    - '(manifest)'

maps:
    - '(maps)'

marketing:
    - '(marketing)'

merge-conflicts:
    - '(merge-conflicts)'

meta:
    - '(meta)'

microformats:
    - '(microformats)'

mockup-available:
    - '(mockup-available)'

mockup-required:
    - '(mockup-required)'

moderation:
    - '(moderation)'

mongodb:
    - '(mongodb)'

monitoring:
    - '(monitoring)'

moving-images:
    - '(moving-images)'

multingual products:
    - '(multingual products)'

needs data analysis:
    - '(needs data analysis)'

needs deployment:
    - '(needs deployment)'

needs help:
    - '(needs help)'

needs investigation:
    - '(needs investigation)'

needs reprocessing:
    - '(needs reprocessing)'

needs tests:
    - '(needs tests)'

needs work:
    - '(needs work)'

new fields:
    - '(new fields)'

nginx:
    - '(nginx)'

no-issue-activity:
    - '(no-issue-activity)'

no-pr-activity:
    - '(no-pr-activity)'

nodejs:
    - '(nodejs)'

non tech:
    - '(non tech)'

not done
nova:
    - '(nova)'

nutrient-levels
nutrients:
    - '(nutrients)'

nutriscore:
    - '(nutriscore)'

nutrition facts:
    - '(nutrition facts)'

observability:
    - '(observability)'

obsolete products:
    - '(obsolete products)'

OCR:
    - '(OCR)'

offline mode:
    - '(offline mode)'

old-products:
    - '(old-products)'

onboarding:
    - '(onboarding)'

open beauty facts:
    - '(open beauty facts)'

open food hunt:
    - '(open food hunt)'

open pet food facts:
    - '(open pet food facts)'

Open Products Facts:
    - '(Open Products Facts)'

openfoodfacts-events:
    - '(openfoodfacts-events)'

organic products:
    - '(organic products)'

origins:
    - '(origins)'

outreachy:
    - '(outreachy)'

P0:
    - '(P0)'

P1 candidate:
    - '(P1 candidate)'

P1:
    - '(P1)'

P2:
    - '(P2)'

P3:
    - '(P3)'

P4:
    - '(P4)'

packager codes:
    - '(packager codes)'

packaging_shapes:
    - '(packaging_shapes)'

packaging:
    - '(packaging)'

pagination:
    - '(pagination)'

palm oil:
    - '(palm oil)'

partners page:
    - '(partners page)'

password reset:
    - '(password reset)'

pathway-to-contribution:
    - '(pathway-to-contribution)'

performance:
    - '(performance)'

Perl:
    - '(Perl)'

personal search:
    - '(personal search)'

polish:
    - '(polish)'

portions:
    - '(portions)'

Portuguese:
    - '(Portuguese)'

power tools for contributors:
    - '(power tools for contributors)'

power-user-script:
    - '(power-user-script)'

preprod:
    - '(preprod)'

prices:
    - '(prices)'

processing:
    - '(processing)'

producer onboarding:
    - '(producer onboarding)'

producers platform:
    - '(producers platform)'

product addition:
    - '(product addition)'

product attributes:
    - '(product attributes)'

product examples:
    - '(product examples)'

product history:
    - '(product history)'

product lists:
    - '(product lists)'

Product Page:
    - '(Product Page)'

product rules:
    - '(product rules)'

product-count page:
    - '(product-count page)'

product-specific issue:
    - '(product-specific issue)'

Products Recalls:
    - '(Products Recalls)'

products without barcodes:
    - '(products without barcodes)'

Products:
    - '(Products)'

products-stored-in-french:
    - '(products-stored-in-french)'

profiles:
    - '(profiles)'

pull-request-available:
    - '(pull-request-available)'

pwa:
    - '(pwa)'

python:
    - '(python)'

Q&A:
    - '(Q&A)'

quality-facet:
    - '(quality-facet)'

quantity:
    - '(quantity)'

question:
    - '(question)'

ready to merge:
    - '(ready to merge)'

Recent changes:
    - '(Recent changes)'

recipes:
    - '(recipes)'

recommendations:
    - '(recommendations)'

refactor:
    - '(refactor)'

release-blocking-issue:
    - '(release-blocking-issue)'

Requires HTTPS:
    - '(Requires HTTPS)'

responsive ux:
    - '(responsive ux)'

road-to-scores:
    - '(road-to-scores)'

robotoff:
    - '(robotoff)'

rtl:
    - '(rtl)'

russian:
    - '(russian)'

salt:
    - '(salt)'

Scan Party:
    - '(Scan Party)'

scan statistics:
    - '(scan statistics)'

science:
    - '(science)'

score explainability:
    - '(score explainability)'

scores:
    - '(scores)'

search ranking:
    - '(search ranking)'

search:
    - '(search)'

seasonality support:
    - '(seasonality support)'

security:
    - '(security)'

segfault:
    - '(segfault)'

SEO:
    - '(SEO)'

server:
    - '(server)'

shortcuts:
    - '(shortcuts)'

sidebar:
    - '(sidebar)'

Signup Page:
    - '(Signup Page)'

slack-notifications:
    - '(slack-notifications)'

solution available:
    - '(solution available)'

spanish:
    - '(spanish)'

special-character-languages:
    - '(special-character-languages)'

special-diets:
    - '(special-diets)'

spellcheck:
    - '(spellcheck)'

Sprint
Stale:
    - '(Stale)'

startup:
    - '(startup)'

static content:
    - '(static content)'

status system:
    - '(status system)'

storage-instructions:
    - '(storage-instructions)'

stores:
    - '(stores)'

📝 story:
    - '(📝 story)'

sugar:
    - '(sugar)'

svg:
    - '(svg)'

tag images:
    - '(tag images)'

tagline:
    - '(tagline)'

Tags.pm:
    - '(Tags.pm)'

Tags:
    - '(Tags)'

task:
    - '(task)'

✔ task:
    - '(✔ task)'

taxonomies rebuild:
    - '(taxonomies rebuild)'

taxonomies:
    - '(taxonomies)'

taxonomy translation:
    - '(taxonomy translation)'

teams:
    - '(teams)'

Template::Toolkit:
    - '(Template::Toolkit)'

tested:
    - '(tested)'

tests:
    - '(tests)'

todo tests:
    - '(todo tests)'

top navigation:
    - '(top navigation)'

👍 Top 10 Issue!:
    - '(👍 Top 10 Issue!)'

traces:
    - '(traces)'

translations:
    - '(translations)'

typing:
    - '(typing)'

Uncommitted assets:
    - '(Uncommitted assets)'

units:
    - '(units)'

untranslatable strings:
    - '(untranslatable strings)'

update-all-products:
    - '(update-all-products)'

us project:
    - '(us project)'

user groups:
    - '(user groups)'

user-management:
    - '(user-management)'

user-support:
    - '(user-support)'

Users:
    - '(Users)'

uservoice:
    - '(uservoice)'

variable-barcodes:
    - '(variable-barcodes)'

vegan:
    - '(vegan)'

vitamins:
    - '(vitamins)'

wiki:
    - '(wiki)'

wikidata:
    - '(wikidata)'

wine:
    - '(wine)'

wontfix:
    - '(wontfix)'

XML
