version: "3.7"
services:
  backend-pro:
    image: productopener-backend-pro-dev
    build:
      context: ../
      dockerfile: ./docker/backend-pro/Dockerfile
      target: runnable
    volumes:
      - type: bind
        source: ./backend-pro-dev/scripts/
        target: /opt/scripts/
      - type: bind
        source: ./backend-pro-dev/conf/Config.pm
        target: /opt/product-opener/lib/ProductOpener/Config.pm
      - type: bind
        source: ./backend-pro-dev/conf/Config2.pm
        target: /opt/product-opener/lib/ProductOpener/Config2.pm
      - type: bind
        source: ./backend-pro-dev/conf/log.conf
        target: /mnt/podata/log.conf
      - type: bind
        source: ./backend-pro-dev/conf/minion_log.conf
        target: /mnt/podata/minion_log.conf
      - type: bind
        source: ./backend-pro-dev/conf/apache.conf
        target: /etc/apache2/sites-enabled/product-opener.conf
      - type: bind
        source: ./backend-pro-dev/conf/po-foreground.sh
        target: /usr/local/bin/po-foreground.sh
      - type: bind
        source: ../
        target: /opt/product-opener/
      - ./logs/apache2-pro:/var/log/apache2
      - ./logs/apache2-pro:/mnt/podata/logs
      - ./logs/apache2-pro:/var/log/httpd
  frontend:
    image: nginx:stable-alpine
    volumes:
      - type: bind
        source: ../
        target: /opt/product-opener/
      - ./logs/nginx:/var/log/nginx
