version: "3.7"
services:
  mongodb:
    image: mongo:4.4
    volumes:
      - dbdata:/var/lib/mongodb
    networks:
      - webnet
    ports:
      - 27017:27017
  memcached:
    image: memcached:1.6-alpine
    networks:
      - webnet
  postgres:
    image: postgres:12-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=minion
  backend:
    image: ghcr.io/openfoodfacts/openfoodfacts-server/backend:${TAG}
    environment:
      - PRODUCT_OPENER_DOMAIN
      - ROBOTOFF_URL
      - GOOGLE_CLOUD_VISION_API_KEY
      - CROWDIN_PROJECT_IDENTIFIER
      - CROWDIN_PROJECT_KEY
      - GEOLITE2_PATH
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    depends_on:
      - mongodb
      - memcached
      - postgres
    volumes:
      - podata:/mnt/podata
      - type: tmpfs
        target: /mnt/podata/mnt
      - product_images:/opt/product-opener/html/images/products
      - html_data:/opt/product-opener/html/data
      - type: bind
        source: ./backend-dev/conf/Config.pm
        target: /opt/product-opener/lib/ProductOpener/Config.pm
      - type: bind
        source: ./backend-dev/conf/Config2.pm
        target: /opt/product-opener/lib/ProductOpener/Config2.pm
      - type: bind
        source: ./backend-dev/conf/log.conf
        target: /mnt/podata/log.conf
      - type: bind
        source: ./backend-dev/conf/minion_log.conf
        target: /mnt/podata/minion_log.conf
      - type: bind
        source: ./backend-dev/conf/apache.conf
        target: /etc/apache2/sites-enabled/product-opener.conf
      - type: bind
        source: ./backend-dev/conf/po-foreground.sh
        target: /usr/local/bin/po-foreground.sh
      - ./logs/apache2:/var/log/apache2
      - ./logs/apache2:/mnt/podata/logs
      - ./logs/apache2:/var/log/httpd      
    command: ["/bin/sh", "/usr/local/bin/po-foreground.sh"]
    networks:
      - webnet
  frontend:
    image: ghcr.io/openfoodfacts/openfoodfacts-server/frontend:${TAG}
    depends_on:
      - backend
    environment:
      - PRODUCT_OPENER_DOMAIN
    volumes:
      - product_images:/opt/product-opener/html/images/products
      - html_data:/opt/product-opener/html/data
      - type: bind
        source: ./frontend-git/conf/nginx.conf
        target: /etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    ports:
      - 80:80
    networks:
      - webnet
networks:
  webnet:
volumes:
  dbdata:
  pgdata:
  podata:
  product_images:
  html_data:
