version: "3.7"
services:
  apache_exporter:
    image: solsson/prometheus-exporter-apache:latest
    command:
      - --scrape_uri=http://backend/server-status?auto
    ports:
      - 9117:9117
    networks:
      - webnet
    depends_on:
      - backend
  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:0.9.0
    command:
      - '-nginx.scrape-uri=http://frontend/nginx_status'
    ports:
      - 9113:9113
    networks:
      - webnet
    depends_on:
      - frontend
  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:v0.10.0
    environment:
    - DATA_SOURCE_NAME=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    networks:
      - webnet
    depends_on:
      - postgres
  filebeat:
    image: elastic/filebeat:7.2.0
    user: root
    environment:
      - ELASTICSEARCH_HOSTS
    volumes:
      - ./conf/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
