name: Link Check Deploy
on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check URLs
        uses: paramt/url-checker@master
        with:
          files: "*.html"

      - uses: LouisBrunner/checks-action@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Check
          status: completed
          conclusion: ${{ steps.check.outputs.conclusion }}
          output: ${{ steps.check.outputs.output }}
