name: Container Image Build CI

on:
  push:
    branches:
      - main
      - deploy-*
    tags: 
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Publish frontend image to Registry
      uses: elgohr/Publish-Docker-Github-Action@3.04
      with:
        name: ${{ github.repository }}/frontend
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        dockerfile: docker/frontend/Dockerfile
        tag_semver: true
        tags: "latest,${{ github.sha }}"
      id: publish_frontend
    - name: Copy frontend output for backend container
      run: |
        CONTAINER=$(docker create ghcr.io/${{ github.repository }}/frontend:${{ github.sha }})
        docker cp $CONTAINER:/opt/product-opener/html/images/icons/dist - > icons.tar
        docker cp $CONTAINER:/opt/product-opener/html/js/dist - > js.tar
        docker cp $CONTAINER:/opt/product-opener/html/css/dist - > css.tar
        tar -xf icons.tar -C ./html/images/icons/
        tar -xf js.tar -C ./html/js/
        tar -xf css.tar -C ./html/css/
        rm icons.tar js.tar css.tar
        docker rm -v $CONTAINER
    - name: Publish backend image to Registry
      uses: elgohr/Publish-Docker-Github-Action@3.04
      with:
        name: ${{ github.repository }}/backend
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        dockerfile: docker/backend/Dockerfile
        tag_semver: true
        tags: "latest,${{ github.sha }}"
