name: Validate translation files
on:
  push:
    branches: '*'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate .po files
        uses: Tar-Minyatur/gettext-validation@master
        with:
          folder: po/
      - name: Ensure unicity in .pot files
        run: msguniq -s -o po/tags/tags.pot po/common/common.pot po/openbeautyfacts/openbeautyfacts.pot po/openfoodfacts/openfoodfacts.pot po/openpetfoodfacts/openpetfoodfacts.pot po/openproductsfacts/openproductsfacts.pot
